name: duffer_project
repository: https://github.com/helightdev/duffer
packages:
  - packages/*
scripts:
  copy-readme:
    name: copy-readme
    description: 'Copies the root-Readme to the duffer package'
    run: cp README.md packages/duffer/README.md

  test:
    description: Run tests in a specific package.
    run: dart test test/*
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test