name: duffer
description: A pure dart library offering support for netty-like byte buffer manipulation and binary serialization via a pickle inspired system
version: 2.3.0
repository: https://github.com/helightdev/duffer

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  meta: ^1.9.1
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
